version: '3.1'
networks:
  jpark-network:
    driver: bridge

services:
  jparkdb:
    image: postgres
    container_name: jparkdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    networks:
      - jpark-network
    volumes:
      - parkdb:/var/lib/postgresql/data

volumes:
  parkdb:
