spring:
  application:
    name: jpark
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER:localhost}:5432/${POSTGRES_DATABASE:jparkdb}
    username: ${POTSGRES_USER:root}
    password: ${POTSGRES_PASSWORD:root}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
server:
  port: 8000

